// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamGate.Worker.Infrastructure;

#nullable disable

namespace StreamGate.Worker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250318201744_V2")]
    partial class V2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assets.Domain.Domain.Entities.SensorConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("LCL")
                        .HasColumnType("real");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("UCL")
                        .HasColumnType("real");

                    b.Property<float>("WarningLowerLevel")
                        .HasColumnType("real");

                    b.Property<float>("WarningUpperLevel")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("SensorConfigs");
                });

            modelBuilder.Entity("Assets.Domain.Domain.Entities.SensorValue", b =>
                {
                    b.Property<Guid>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alert")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Config")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("SensorId");

                    b.ToTable("SensorValues");
                });
#pragma warning restore 612, 618
        }
    }
}
